services:
  webai:
    build:
      context: .
      secrets:
        - lacework_toml
    container_name: webai-serve
    ports:
      - "45321:45321"
    env_file:
      - .env
    volumes:
      - ~/.lacework.toml:/root/.lacework.toml:ro
      - ~/claude_cnapp/lql/lql_queries:/lql_queries:ro
    restart: unless-stopped

secrets:
  lacework_toml:
    file: ~/.lacework.toml
